---
title: "Quiz2_takehome"
author: "Clara Mugnai"
date: "1/31/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# All work presented is my own, and I have followed all rules for collaboration.”

Clara Mugnai

```{r}
library(tidyverse)
library(readxl)
df <- read_excel("data/slu_graduates_17_21.xlsx")

## fixes error in the data
df <- df %>% mutate(across(everything(),
                           .fns = ~replace(., . ==  "STATS" , "STAT")))
```

# Question 1:

```{r}
df_stat = df %>%  filter(major1 == "STAT" | major2 == "STAT" | major3 == "STAT") %>% 
  pivot_longer(c(3:8), values_to = "discipline", names_to = "type") %>% 
  filter(type == "major1" | type == "major2" | type == "major3") %>%
  filter(discipline != "STAT" & !is.na(discipline))  %>%
  group_by(discipline) %>%
  summarise(nstudents = n()) %>%
  arrange(desc(nstudents)) %>%
  mutate(discipline = fct_reorder(discipline, nstudents))

ggplot(data = df_stat, aes(x = nstudents,y = discipline)) + geom_col() + labs(x = "number of students in major", y = "Major, in addition to STAT major")
```

# Question 2:

```{r}
df_female = df %>% pivot_longer(c(3:8), values_to = "discipline", names_to = "type") %>% 
  filter(type == "major1" | type == "major2" | type == "major3") %>%  filter(!is.na(discipline)) %>%
  group_by(discipline, sex) %>%
  summarise(nstudents = n()) %>% 
  ungroup() %>%
  group_by(discipline) %>%
    mutate(ntotal = sum(nstudents)) %>% 
  filter(ntotal >= 50) %>% 
  mutate(propfemale = nstudents / ntotal) %>%
  filter(sex == "F") %>%
  arrange(desc(propfemale)) %>%
  mutate(discipline = fct_reorder(discipline, propfemale))

ggplot(df_female, aes(x = reorder(discipline,propfemale), y = propfemale)) +
  geom_point() +
  geom_segment(aes(x = reorder(discipline,propfemale), xend = reorder(discipline,propfemale), y=0, yend = propfemale)) + coord_flip() + labs(x = "Major", y = "Proportion of females in major")
```

